task_name: ${task.name}

experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: ''

seed: 42

torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

physics_engine: 'physx'

pipeline: 'gpu'

sim_device: 'cuda:0'

rl_device: 'cuda:0'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
# used to set checkpoint path
checkpoint: ''
# set to True to use multi-gpu horovod training
multi_gpu: False

# disables rendering
headless: False

# set default task and default training config based on task
defaults:
  - task: BallBalance
  - hydra/job_logging: disabled
  - _self_

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .